[build]
  publish = "build/web"
  command = """
    git clone https://github.com/flutter/flutter.git -b stable --depth 1 && \
    export PATH="$PATH:`pwd`/flutter/bin" && \
    flutter doctor && \
    flutter build web --release
  """

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
